/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetsNewRouteImport } from './routes/pets/new'
import { Route as PetsPetIdRouteImport } from './routes/pets/$petId'
import { ServerRoute as ApiUsersServerRouteImport } from './routes/api/users'
import { ServerRoute as ApiPetsServerRouteImport } from './routes/api/pets'
import { ServerRoute as ApiAnimalsServerRouteImport } from './routes/api/animals'
import { ServerRoute as ApiUsersUserIdServerRouteImport } from './routes/api/users.$userId'
import { ServerRoute as ApiPetsPetIdServerRouteImport } from './routes/api/pets/$petId'
import { ServerRoute as ApiPetsPetIdVaccineServerRouteImport } from './routes/api/pets/$petId.vaccine'
import { ServerRoute as ApiPetsPetIdLabsServerRouteImport } from './routes/api/pets/$petId.labs'
import { ServerRoute as ApiPetsPetIdAllergyServerRouteImport } from './routes/api/pets/$petId.allergy'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersServerRoute = ApiUsersServerRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPetsServerRoute = ApiPetsServerRouteImport.update({
  id: '/api/pets',
  path: '/api/pets',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAnimalsServerRoute = ApiAnimalsServerRouteImport.update({
  id: '/api/animals',
  path: '/api/animals',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersUserIdServerRoute = ApiUsersUserIdServerRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersServerRoute,
} as any)
const ApiPetsPetIdServerRoute = ApiPetsPetIdServerRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => ApiPetsServerRoute,
} as any)
const ApiPetsPetIdVaccineServerRoute =
  ApiPetsPetIdVaccineServerRouteImport.update({
    id: '/vaccine',
    path: '/vaccine',
    getParentRoute: () => ApiPetsPetIdServerRoute,
  } as any)
const ApiPetsPetIdLabsServerRoute = ApiPetsPetIdLabsServerRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => ApiPetsPetIdServerRoute,
} as any)
const ApiPetsPetIdAllergyServerRoute =
  ApiPetsPetIdAllergyServerRouteImport.update({
    id: '/allergy',
    path: '/allergy',
    getParentRoute: () => ApiPetsPetIdServerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pets/$petId' | '/pets/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pets/$petId' | '/pets/new'
  id: '__root__' | '/' | '/pets/$petId' | '/pets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
  PetsNewRoute: typeof PetsNewRoute
}
export interface FileServerRoutesByFullPath {
  '/api/animals': typeof ApiAnimalsServerRoute
  '/api/pets': typeof ApiPetsServerRouteWithChildren
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/pets/$petId': typeof ApiPetsPetIdServerRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/pets/$petId/allergy': typeof ApiPetsPetIdAllergyServerRoute
  '/api/pets/$petId/labs': typeof ApiPetsPetIdLabsServerRoute
  '/api/pets/$petId/vaccine': typeof ApiPetsPetIdVaccineServerRoute
}
export interface FileServerRoutesByTo {
  '/api/animals': typeof ApiAnimalsServerRoute
  '/api/pets': typeof ApiPetsServerRouteWithChildren
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/pets/$petId': typeof ApiPetsPetIdServerRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/pets/$petId/allergy': typeof ApiPetsPetIdAllergyServerRoute
  '/api/pets/$petId/labs': typeof ApiPetsPetIdLabsServerRoute
  '/api/pets/$petId/vaccine': typeof ApiPetsPetIdVaccineServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/animals': typeof ApiAnimalsServerRoute
  '/api/pets': typeof ApiPetsServerRouteWithChildren
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/pets/$petId': typeof ApiPetsPetIdServerRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/pets/$petId/allergy': typeof ApiPetsPetIdAllergyServerRoute
  '/api/pets/$petId/labs': typeof ApiPetsPetIdLabsServerRoute
  '/api/pets/$petId/vaccine': typeof ApiPetsPetIdVaccineServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/animals'
    | '/api/pets'
    | '/api/users'
    | '/api/pets/$petId'
    | '/api/users/$userId'
    | '/api/pets/$petId/allergy'
    | '/api/pets/$petId/labs'
    | '/api/pets/$petId/vaccine'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/animals'
    | '/api/pets'
    | '/api/users'
    | '/api/pets/$petId'
    | '/api/users/$userId'
    | '/api/pets/$petId/allergy'
    | '/api/pets/$petId/labs'
    | '/api/pets/$petId/vaccine'
  id:
    | '__root__'
    | '/api/animals'
    | '/api/pets'
    | '/api/users'
    | '/api/pets/$petId'
    | '/api/users/$userId'
    | '/api/pets/$petId/allergy'
    | '/api/pets/$petId/labs'
    | '/api/pets/$petId/vaccine'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAnimalsServerRoute: typeof ApiAnimalsServerRoute
  ApiPetsServerRoute: typeof ApiPetsServerRouteWithChildren
  ApiUsersServerRoute: typeof ApiUsersServerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/pets': {
      id: '/api/pets'
      path: '/api/pets'
      fullPath: '/api/pets'
      preLoaderRoute: typeof ApiPetsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/animals': {
      id: '/api/animals'
      path: '/api/animals'
      fullPath: '/api/animals'
      preLoaderRoute: typeof ApiAnimalsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdServerRouteImport
      parentRoute: typeof ApiUsersServerRoute
    }
    '/api/pets/$petId': {
      id: '/api/pets/$petId'
      path: '/$petId'
      fullPath: '/api/pets/$petId'
      preLoaderRoute: typeof ApiPetsPetIdServerRouteImport
      parentRoute: typeof ApiPetsServerRoute
    }
    '/api/pets/$petId/vaccine': {
      id: '/api/pets/$petId/vaccine'
      path: '/vaccine'
      fullPath: '/api/pets/$petId/vaccine'
      preLoaderRoute: typeof ApiPetsPetIdVaccineServerRouteImport
      parentRoute: typeof ApiPetsPetIdServerRoute
    }
    '/api/pets/$petId/labs': {
      id: '/api/pets/$petId/labs'
      path: '/labs'
      fullPath: '/api/pets/$petId/labs'
      preLoaderRoute: typeof ApiPetsPetIdLabsServerRouteImport
      parentRoute: typeof ApiPetsPetIdServerRoute
    }
    '/api/pets/$petId/allergy': {
      id: '/api/pets/$petId/allergy'
      path: '/allergy'
      fullPath: '/api/pets/$petId/allergy'
      preLoaderRoute: typeof ApiPetsPetIdAllergyServerRouteImport
      parentRoute: typeof ApiPetsPetIdServerRoute
    }
  }
}

interface ApiPetsPetIdServerRouteChildren {
  ApiPetsPetIdAllergyServerRoute: typeof ApiPetsPetIdAllergyServerRoute
  ApiPetsPetIdLabsServerRoute: typeof ApiPetsPetIdLabsServerRoute
  ApiPetsPetIdVaccineServerRoute: typeof ApiPetsPetIdVaccineServerRoute
}

const ApiPetsPetIdServerRouteChildren: ApiPetsPetIdServerRouteChildren = {
  ApiPetsPetIdAllergyServerRoute: ApiPetsPetIdAllergyServerRoute,
  ApiPetsPetIdLabsServerRoute: ApiPetsPetIdLabsServerRoute,
  ApiPetsPetIdVaccineServerRoute: ApiPetsPetIdVaccineServerRoute,
}

const ApiPetsPetIdServerRouteWithChildren =
  ApiPetsPetIdServerRoute._addFileChildren(ApiPetsPetIdServerRouteChildren)

interface ApiPetsServerRouteChildren {
  ApiPetsPetIdServerRoute: typeof ApiPetsPetIdServerRouteWithChildren
}

const ApiPetsServerRouteChildren: ApiPetsServerRouteChildren = {
  ApiPetsPetIdServerRoute: ApiPetsPetIdServerRouteWithChildren,
}

const ApiPetsServerRouteWithChildren = ApiPetsServerRoute._addFileChildren(
  ApiPetsServerRouteChildren,
)

interface ApiUsersServerRouteChildren {
  ApiUsersUserIdServerRoute: typeof ApiUsersUserIdServerRoute
}

const ApiUsersServerRouteChildren: ApiUsersServerRouteChildren = {
  ApiUsersUserIdServerRoute: ApiUsersUserIdServerRoute,
}

const ApiUsersServerRouteWithChildren = ApiUsersServerRoute._addFileChildren(
  ApiUsersServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PetsPetIdRoute: PetsPetIdRoute,
  PetsNewRoute: PetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAnimalsServerRoute: ApiAnimalsServerRoute,
  ApiPetsServerRoute: ApiPetsServerRouteWithChildren,
  ApiUsersServerRoute: ApiUsersServerRouteWithChildren,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
